### ISSUE TITLE
[Wishlist] Additional compiler-specific features

### ISSUE THREAD

**Issue by stertingen** [nemequ/hedley#47]
Hello, I currently consider migrating a self-made compiler abstraction header to hedley. There are a few things missing that I would put onto a wishlist:

- `__attribute__((optimize(x)))`
- `__attribute__((init_priority(x)))`
- `__attribute__((constructor))`,  `__attribute__((constructor(x)))`
- `__attribute__((destructor))`,  `__attribute__((destructor(x)))`
- `__attribute__((weak, alias(x)))`
- `__attribute__((section(x)))`
- `__attribute__((packed))`
- `alignas`, `_Alignas`, `__attribute__((aligned(x)))`

While above attributes are usually not used for Linux/Windows applications, they come in handy for embedded devlopment.

**Comment by nemequ** [comment]
For optimization macros, see #6.

Alignment is a bit of a rabbit hole.  I have [some alignment code in SIMDe](https://github.com/simd-everywhere/simde/blob/master/simde/simde-align.h) which you can use if you want to.  That's the most portable solution I'm aware of, and even it is a bit iffy.

The other ideas (plus the alignment stuff) aren't safe since they alter program behavior in ways we can't emulate in other compilers.  See the "[Can you add support for «feature»?](https://nemequ.github.io/hedley/#faq-feature-acceptability)" FAQ question on the Hedley web page.

A quick note about packed: I would suggest `#pragma pack(push,n)` / `#pragma pack(pop)` instead of `__attribute__((__packed__))` since more compilers (including MSVC) support the push/pop syntax.
