### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by eustas** [nemequ/hedley#7]
https://github.com/nemequ/hedley/blob/18dd7a5420340cdd23310b6a6790823a635ded21/hedley.h#L298

This is the only mention of HED**EL**Y_xxx in the whole project.

**Comment by eustas** [comment]
https://github.com/nemequ/hedley/blob/18dd7a5420340cdd23310b6a6790823a635ded21/hedley.h#L828
Another typo candidate - `no return` defined in the middle of `pure`

**Comment by eustas** [comment]
https://github.com/nemequ/hedley/blob/18dd7a5420340cdd23310b6a6790823a635ded21/hedley.h#L932
Also looks suspicious - "inline" as a fallback for "never inline"

**Comment by eustas** [comment]
https://github.com/nemequ/hedley/blob/18dd7a5420340cdd23310b6a6790823a635ded21/hedley.h#L952
Unlike everywhere else `defined(__TI_GNU_ATTRIBUTE_SUPPORT__)` is missing?

**Comment by nemequ** [comment]
Thanks, it's *really* nice to have another pair of eyes on this. Testing this project is annoyingly difficult since errors often mean the macro is defined to nothing, and I don't have access to many compilers (especially obsolete versions of proprietary compilers).

I think the last one is right; I seem to remember doing that on purpose because TI doesn't allow EABI w/o `--gcc`. That said, I don't think adding `defined(__TI_GNU_ATTRIBUTE_SUPPORT__)` would hurt anything, so it may be better to be defensive about it.

The others are definitely wrong. I just pushed a fix to the dev branch, I want to try to add tests for all macros before the next release. I don't I could have detected any of these, but still… there should be tests.
